Repository Arctic-Cuyes/ZonaHub, pull requests merged in 2023-03, with the labels that each got.

#8 Feat/jc 7/reorganize folders
  lib/src/app.dart
  lib/src/views/home/home.dart
  lib/src/views/home/home_recent.dart
  lib/src/views/post/post_detail.dart
  lib/src/views/post/post_new.dart
Labels: good first issue

#11 Fix/bm 10/notifications folder name
  lib/src/app.dart
  lib/src/views/notifications/notifications.dart
  pubspec.lock
Labels: good first issue

#21 Feat/be 14/add app icon
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: enhancement

#23 Feat/be 2/add map
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/src/app.dart
  lib/src/views/map/map.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_examples.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#24 BREAKING CHANGE: Feat/be 5/handle permissions
  android/app/src/main/AndroidManifest.xml
  lib/src/app.dart
  lib/src/views/auth/auth_controller.dart
  lib/src/views/auth/login.dart
  lib/src/views/auth/register.dart
  lib/src/views/map/map.dart
  lib/src/views/permissions/permission.dart
  lib/src/views/permissions/permission_controller.dart
  lib/src/views/root.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#32 Feat/be 29/add gps functionality
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/src/services/gps_service.dart
  lib/src/views/map/map.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/permissions/permission.dart
  lib/src/views/root.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#36 add: email and password sign in provider
  lib/src/app.dart
  lib/src/services/Auth/auth_controller.dart
  lib/src/services/Auth/sign_in_provider.dart
  lib/src/views/auth/login.dart
Labels: enhancement

#37 Feat/be 34/add custom markers
  assets/markers/marker_aviso.png
  assets/markers/marker_ayuda.png
  assets/markers/marker_evento.png
  assets/markers/marker_pet.png
  assets/markers/marker_salud.png
  assets/veterinary.png
  lib/src/services/custom_markers_service.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_examples.dart
  pubspec.yaml
Labels: enhancement

#39 Feat/be 38/add cards
  lib/src/views/auth/login.dart
  lib/src/views/map/map.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_bottom_sheet.dart
  lib/src/views/map/marker_examples.dart
Labels: bug, enhancement

#41 Feat/be 22/add internet validation
  lib/src/components/warnings/internet_conn.dart
  lib/src/services/connectivity_service.dart
  lib/src/services/internet_valid_service.dart
  lib/src/views/map/map.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_examples.dart
  lib/src/views/root.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#44 add: blank page while waiting isSignedIn value and loader after sign in
  lib/src/app.dart
  lib/src/components/drawer.dart
  lib/src/views/auth/login.dart
Labels: enhancement

#51 Feat/be 43/add lazy markers
  lib/src/constants/custom_marker_images.dart
  lib/src/services/lazy_markers_service.dart
  lib/src/views/map/map.dart
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_examples.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, question

#54 fix: login flow improved
  lib/src/app.dart
  lib/src/components/forms/pages_login.dart
  lib/src/views/auth/screens/login_screen.dart
  lib/src/views/auth/screens/register_screen.dart
Labels: enhancement

#62 add: GeoData deserialization
  lib/src/models/geo/geo_data.dart
  lib/src/models/post_model.dart
Labels: enhancement

#69 Feat/jc 58/add user profile
  android/app/src/main/AndroidManifest.xml
  lib/src/components/drawer.dart
  lib/src/services/Storage/firebase_storage.dart
  lib/src/services/user_service.dart
  lib/src/views/profile/profile.dart
Labels: enhancement

#76 Feat/be 63/add posts form
  lib/src/models/post_model.dart
  lib/src/services/Map/gps_service.dart
  lib/src/services/Storage/firebase_storage.dart
  lib/src/services/reverse_geocode_service.dart
  lib/src/services/tag_service.dart
  lib/src/views/home/home.dart
  lib/src/views/post/address_autocomplete.dart
  lib/src/views/post/post_new.dart
  lib/src/views/post/select_location.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#81 fix: markers on map
  lib/src/views/map/map_controller.dart
  lib/src/views/map/marker_bottom_sheet.dart
Labels: enhancement

#88 Tags on Post.
  lib/src/components/post/post.dart
  lib/src/components/post/tagsComponent.dart
  lib/src/constants/tags_list.dart
  lib/src/views/map/marker_bottom_sheet.dart
  pubspec.lock
Labels: enhancement

#97 Fix/bm 96/to inactive post bug
  lib/src/services/post_service.dart
  lib/src/views/post/post_new.dart
Labels: bug

#98 Feat/be 95/update logo
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/launch_image.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/launch_image.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/launch_image.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/launch_image.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/launch_image.png
  assets/images/ZH_Logo.png
  assets/images/apollama.png
  lib/src/app.dart
  lib/src/components/global/button.dart
  lib/src/components/post/tagsComponent.dart
  lib/src/constants/images.dart
  lib/src/views/auth/welcome.dart
  lib/src/views/root.dart
Labels: enhancement
